### PR TITLE
fix: add missing parameter, change incorrect member variable name

### PR DESCRIPTION
**Pull request by hampuslavin**
Fixes:
 - Missing `session` parameter in `updateRow` call
 - Unless I'm missing something, the member variable referenced in the docs, `authorizedUserId`, doesn't exist (anymore)?
   - I changed it to `authenticatedUserId` which is the existing one
   - Is this just a typo and should I change it in all versions of the docs? Or was this a breaking change at some point?

### CODE REVIEW

**Review by SandPod — APPROVED** [review]
You are correct, authorizedUserId doesn't exist.
And I can't seem to find it in any of the older tags of the repo either so feel free to change on all version back to 1.0.0 (before that we don't have a tag so I'm not sure if it change names back then).

I'll approve and merge once the change is applied to 1.1.0 and 1.0.0

Thank you for the corrections 🙏

**Review by SandPod — CHANGES_REQUESTED** [review]
Too quick on the trigger. Apply the `authorizedUserId` change on `1.1.0` and `1.0.0` and I'll approve and merge :)

**Comment by hampuslavin** [comment]
@SandPod Done! ✅

**Review by SandPod — APPROVED** [review]
Thank you for this fix! 🙏

**Pull request merged**
